Type: Jupyter Notebook Extension
Compatibility: 3.x, 4.x, 5.x, 6.x
Name: Move imports to top cell
Main: main.js
Link: README.md
Description: |
  Finds all imports in the notebook and move them to its topmost cell.
Parameters:
- none
